Update index.md
修正bookinfo中文示例yaml与英文不一致，出现 
Command "create" is deprecated, Use `kubectl create` instead (see https://kubernetes.io/docs/tasks/tools/install-kubectl)
Error: 1 error occurred:
* validation error: target name "" must be a valid label